force-app/main/default/objects/Document_Generation_Log__c/Document_Generation_Log__c.object-meta.xml
<CustomObject>
    <label>Document Generation Log</label>
    <nameField>
        <displayFormat>#{DD}/{MM}/{YYYY}: {0}</displayFormat>
        <label>Document Generation Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Generation Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Generation_Log__c/fields/Complete_Log__c.field-meta.xml
<CustomField>
    <fullName>Complete_Log__c</fullName>
    <label>Complete Log</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Document_Generation_Log__c/fields/Current_Signer_Count__c.field-meta.xml
<CustomField>
    <fullName>Current_Signer_Count__c</fullName>
    <defaultValue>&quot;0&quot;</defaultValue>
    <label>Current Signer Count</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Generation_Log__c/fields/Document_Require_E_Signature__c.field-meta.xml
<CustomField>
    <fullName>Document_Require_E_Signature__c</fullName>
    <formula>Template_Record__r.Document_Require_E_Signature__c</formula>
    <label>Document Require E-Signature</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Document_Generation_Log__c/fields/Latest_ContentVersion_Id__c.field-meta.xml
<CustomField>
    <fullName>Latest_ContentVersion_Id__c</fullName>
    <label>Latest ContentVersion Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Generation_Log__c/fields/Post_Processing_Email__c.field-meta.xml
<CustomField>
    <fullName>Post_Processing_Email__c</fullName>
    <formula>Template_Record__r.Receiver_Email__c</formula>
    <label>Post Processing Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Generation_Log__c/fields/Post_Signature_Processing__c.field-meta.xml
<CustomField>
    <fullName>Post_Signature_Processing__c</fullName>
    <formula>TEXT(Template_Record__r.Template_Output__c)</formula>
    <label>Post Signature Processing</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Generation_Log__c/fields/Signer_Email__c.field-meta.xml
<CustomField>
    <fullName>Signer_Email__c</fullName>
    <label>Signer Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Generation_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Document Generated</fullName>
            </value>
            <value>
                <fullName>Document Sent on Email</fullName>
            </value>
            <value>
                <fullName>Document Signing Completed</fullName>
            </value>
            <value>
                <fullName>Document Signing Pending</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Initiated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Generation_Log__c/fields/Template_Record__c.field-meta.xml
<CustomField>
    <fullName>Template_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Template Record</label>
    <referenceTo>Document_Template__c</referenceTo>
    <relationshipLabel>Document Generation Logs</relationshipLabel>
    <relationshipName>Document_Generation_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Signer__c/Document_Signer__c.object-meta.xml
<CustomObject>
    <label>Document Signer</label>
    <nameField>
        <label>Document Signer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Signers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Signer__c/fields/Document_Template__c.field-meta.xml
<CustomField>
    <fullName>Document_Template__c</fullName>
    <label>Document Template</label>
    <referenceTo>Document_Template__c</referenceTo>
    <relationshipLabel>Document Signers</relationshipLabel>
    <relationshipName>Document_Signers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Document_Template__c/Document_Template__c.object-meta.xml
<CustomObject>
    <description>This object will store the templates to be used to generate documents.</description>
    <label>Document Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Template__c/fields/Document_Require_E_Signature__c.field-meta.xml
<CustomField>
    <fullName>Document_Require_E_Signature__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Document Require E-Signature</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Document_Template__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log_Records__c/Log_Records__c.object-meta.xml
<CustomObject>
    <label>Log Record</label>
    <nameField>
        <displayFormat>LR-{0}</displayFormat>
        <label>Log Records Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Log_Records__c/fields/Additional_Information__c.field-meta.xml
<CustomField>
    <fullName>Additional_Information__c</fullName>
    <label>Additional Information</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Records__c/fields/Document_Generation_Log__c.field-meta.xml
<CustomField>
    <fullName>Document_Generation_Log__c</fullName>
    <label>Document Generation Log</label>
    <referenceTo>Document_Generation_Log__c</referenceTo>
    <relationshipLabel>Log Records</relationshipLabel>
    <relationshipName>Log_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Log_Records__c/fields/Salesforce_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Record_Id__c</fullName>
    <label>Salesforce Record Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Records__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initiation</fullName>
            </value>
            <value>
                <fullName>OTP Requested</fullName>
            </value>
            <value>
                <fullName>OTP Verified</fullName>
            </value>
            <value>
                <fullName>Document sent for signature</fullName>
            </value>
            <value>
                <fullName>Document signed</fullName>
            </value>
            <value>
                <fullName>Document sent on email</fullName>
            </value>
            <value>
                <fullName>Document completed</fullName>
            </value>
            <value>
                <fullName>Document Linked to Salesforce Record</fullName>
            </value>
            <value>
                <fullName>OTP Verification Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/docGenLogTriggerHandler.cls
public class docGenLogTriggerHandler {
    public static boolean bByPassTrigger = false;
    public static void beforeInsert(List<Document_Generation_Log__c> lstNewRecords){
        //generateLog(lstNewRecords);
    }
    public static void afterInsert(List<Document_Generation_Log__c> lstNewRecords, Map<Id, Document_Generation_Log__c> mapOldRecords){
        //if(!bByPassTrigger)
        //initiateLifeCycle(lstNewRecords);
        generateLog(lstNewRecords);
    }
    public static void beforeUpdate(List<Document_Generation_Log__c> lstNewRecords, Map<Id, Document_Generation_Log__c> mapOldRecords){
        
    }
    public static void afterUpdate(List<Document_Generation_Log__c> lstNewRecords, Map<Id, Document_Generation_Log__c> mapOldRecords){
        if(!bByPassTrigger){
        	calculateNextSigner(lstNewRecords);
        }
    }
    
    public static void initiateLifeCycle(List<Document_Generation_Log__c> lstNewRecords){
        List<Document_Generation_Log__c> lstSigningDocuments = new List<Document_Generation_Log__c>();
        List<Document_Generation_Log__c> lstCompletionDocuments = new List<Document_Generation_Log__c>();
        
        for(Document_Generation_Log__c objLog : lstNewRecords){
            //If Document has Signer, Add to Signing Documents
            if(objLog.Document_Require_E_Signature__c){
               lstSigningDocuments.add(objLog);
            } else {
               lstCompletionDocuments.add(objLog);
            }
            
        }
        if(!lstSigningDocuments.isEmpty()){
            calculateNextSigner(lstSigningDocuments);
        } 
        if(!lstCompletionDocuments.isEmpty()){
           documentCompletion(lstCompletionDocuments);
        }
    }
    
    public static void calculateNextSigner(List<Document_Generation_Log__c> lstRecords){  
        //Get Template ID
        List<Id> lstTemplateId = new List<Id>();
        for(Document_Generation_Log__c objLog : lstRecords){
            lstTemplateId.add(objLog.Template_Record__c);
        }
        List<Document_Generation_Log__c> lstSigningDocuments = new List<Document_Generation_Log__c>();
        List<Document_Generation_Log__c> lstCompletionDocuments = new List<Document_Generation_Log__c>();
        //Get Template Details
        Map<Id, Document_Template__c> mapTemplates = new Map<Id, Document_Template__c>([Select Id, (Select Id,Name, Signer_Email__c from Document_Signers__r) From Document_Template__c WHERE Id IN :lstTemplateId]);      
        
        for(Document_Generation_Log__c objLog : lstRecords){
            Document_Template__c objTemplate = mapTemplates.containsKey(objLog.Template_Record__c)?mapTemplates.get(objLog.Template_Record__c):null;
            if(objTemplate != null){
                List<Document_Signer__c> lstSigners = objTemplate.Document_Signers__r;
                //If More Signing Exist
                if(Integer.valueOf(objLog.Current_Signer_Count__c) < lstSigners.size()){
                    Document_Signer__c objCurrentSigner = lstSigners[Integer.valueOf(objLog.Current_Signer_Count__c)];
                    //Clone Existing record
                    Document_Generation_Log__c objNewLog = new Document_Generation_Log__c();
                    objNewLog.Id = objLog.Id;
                    objNewLog.Signer_Name__c = objCurrentSigner.Name;
                    objNewLog.Signer_Email__c = objCurrentSigner.Signer_Email__c;
                    lstSigningDocuments.add(objNewLog);
                } else { //Signing Done
                    lstCompletionDocuments.add(objLog);
                }
                
            }
        }
        if(!lstSigningDocuments.isEmpty()){
            sendDocumentForSignature(lstSigningDocuments);
        } 
        if(!lstCompletionDocuments.isEmpty()){
           documentCompletion(lstCompletionDocuments);
        }
    }
    
     
    public static void sendDocumentForSignature(List<Document_Generation_Log__c> lstRecords){ 
        List<Messaging.SingleEmailMessage> lstEmailsToSend = new List<Messaging.SingleEmailMessage>();  
        List<Document_Generation_Log__c> lstLogToUpdate = new List<Document_Generation_Log__c>(); 
        List<Log_Records__c> lstLog = new List<Log_Records__c>(); 
        Document_Generation_Log__c objNewLog = new Document_Generation_Log__c();
        for(Document_Generation_Log__c objLog: lstRecords){
            //Change the Status of Log Record: 
            objNewLog.Id = objLog.Id;
            objNewLog.Status__c = 'Document Signing Pending';
            objNewLog.Complete_Log__c = 'Document Sent for Signature at: '+System.now()+' to '+objLog.Signer_Name__c+' at '+objLog.Signer_Email__c+'\n'+objLog.Complete_Log__c;
            objNewLog.Signer_Email__c = objLog.Signer_Email__c;
            objNewLog.Signer_Name__c = objLog.Signer_Name__c;
            lstLogToUpdate.add(objNewLog); 
            
            Log_Records__c objLogRecord = new Log_Records__c();
           	objLogRecord.Type__c = 'Document Sent for Signature';
            objLogRecord.Salesforce_Record_Id__c = objNewLog.Salesforce_Record_Id__c;
            objLogRecord.Document_Generation_Log__c = objLog.Id;
            objLogRecord.Additional_Information__c ='Email: '+objLog.Signer_Email__c+'\n Name:'+objLog.Signer_Name__c;
            
            lstLog.add(objLogRecord);
            
            String sToEmail = objLog.Signer_Email__c;
            String sUserName = objLog.Signer_Name__c;             
            String sLink = '';
            
            EmailTemplate emTemp = [Select Id, HTMLValue, Subject from EmailTemplate Where Name = 'Document Generation- Template for e-signature'][0];
            
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setToAddresses(new List<String>{sToEmail});
			String sHTMLBody = emTemp.HTMLValue;
            String sURLParam = (String)documentGeneratorCtrl.encodeDecodeURL(new Map<String, Object>{'operation'=> 'encode', 'recordId'=> objLog.Id}).get('param');
            String sURL = System.Label.pspdfKit_ExternalPublicLink+'?document='+sURLParam;
            sHTMLBody = sHTMLBody.replaceAll('Document_Link', sURL);
            sHTMLBody = sHTMLBody.replaceAll('Signer_Name', sUserName);
            mail.setHtmlBody(sHTMLBody);
            //mail.setSubject(emTemp.Subject);
            mail.setSubject('Request for Document Validation and Signature');
            lstEmailsToSend.add(mail);   
            
        }
        if(!lstEmailsToSend.isEmpty()){
            Messaging.sendEmail(lstEmailsToSend);
        }
        if(!lstLogToUpdate.isEmpty()){
            bByPassTrigger = true;
			update lstLogToUpdate;            
        }
        if(!lstLog.isEmpty()){
            insert lstLog;
        }
    }
    
    public static void documentCompletion(List<Document_Generation_Log__c> lstRecords){ 
        Boolean bUpdateLog= false;
        List<Messaging.SingleEmailMessage> lstEmailsToSend = new List<Messaging.SingleEmailMessage>();  
        List<ContentDocumentLink> lstLinksToCreate = new List<ContentDocumentLink>();
        List<Document_Generation_Log__c> lstLogToUpdate = new List<Document_Generation_Log__c>(); 
        Document_Generation_Log__c objNewLog = new Document_Generation_Log__c();
        List<Log_Records__c> lstLog = new List<Log_Records__c>();
        for(Document_Generation_Log__c objLog: lstRecords){
            if(objLog.Post_Signature_Processing__c == 'Create Salesforce file record' || objLog.Post_Signature_Processing__c == 'Both'){
                //Change the Status of Log Record: 
                objNewLog.Id = objLog.Id;
            	objNewLog.Status__c = 'Completed';
            	objNewLog.Complete_Log__c = 'Document Linked to Record: '+objLog.Salesforce_Record_Id__c+' at '+System.now()+'\n'+objLog.Complete_Log__c;
	            bUpdateLog = true;
                
                Log_Records__c objLogRecord = new Log_Records__c();
            	objLogRecord.Type__c = 'Document Linked to Salesforce Record';
                objLogRecord.Salesforce_Record_Id__c = objNewLog.Salesforce_Record_Id__c;
            	objLogRecord.Document_Generation_Log__c = objLog.Id;
                objLogRecord.Additional_Information__c ='Record: '+objNewLog.Salesforce_Record_Id__c;
            	lstLog.add(objLogRecord);
                
                ContentVersion objCV = [Select Id,ContentDocumentId from ContentVersion Where Id =: objLog.Latest_ContentVersion_Id__c][0];
                
                ContentDocumentLink objnewCDL = new ContentDocumentLink();
                objnewCDL.ContentDocumentId = objCV.ContentDocumentId;
                objnewCDL.LinkedEntityId = objLog.Salesforce_Record_Id__c;
                objnewCDL.ShareType = 'V';
                objnewCDL.Visibility = 'AllUsers';
                lstLinksToCreate.add(objnewCDL);
                
            }
            if(objLog.Post_Signature_Processing__c == 'Send file as email attachment' || objLog.Post_Signature_Processing__c == 'Both'){
                //Change the Status of Log Record: 
                objNewLog.Id = objLog.Id;
            	objNewLog.Status__c = 'Completed';
                
                Log_Records__c objLogRecord = new Log_Records__c();
            	objLogRecord.Type__c = 'Document sent on email';
                objLogRecord.Document_Generation_Log__c = objNewLog.Id;
                objLogRecord.Additional_Information__c ='Email: '+objLog.Post_Processing_Email__c;
            	lstLog.add(objLogRecord);
	            objNewLog.Complete_Log__c = 'Document Sent at: '+System.now()+' to '+objLog.Post_Processing_Email__c+'\n'+objLog.Complete_Log__c;
                bUpdateLog = true;
            
                String sToEmail = objLog.Post_Processing_Email__c;
                String sUserName = objLog.Signer_Name__c;             
                String sLink = '';
                
                
                EmailTemplate emTemp = [Select Id, HTMLValue, Subject from EmailTemplate Where Name = 'Document Generation- Template for document completion'][0];
				
                ContentVersion objCV = [Select Id,ContentDocument.LatestPublishedVersionId,VersionData from ContentVersion Where Id =: objLog.Latest_ContentVersion_Id__c][0];
            
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                mail.setToAddresses(new List<String>{sToEmail});
                //mail.setHtmlBody(emTemp.HTMLValue+'\n\n\n'+EncodingUtil.base64Encode(objCV.VersionData));
                mail.setHtmlBody(emTemp.HTMLValue);
                mail.setSubject(emTemp.Subject);
                
                mail.setEntityAttachments(new List<String> {objLog.Latest_ContentVersion_Id__c});
                
                
                lstEmailsToSend.add(mail);   
            }
            if(bUpdateLog){
                Log_Records__c objLogRecord = new Log_Records__c();
            	objLogRecord.Type__c = 'Document completed';
                objLogRecord.Document_Generation_Log__c = objNewLog.Id;
                objLogRecord.Additional_Information__c ='Completed on '+System.now();
            	lstLog.add(objLogRecord);
                
                bUpdateLog = true;
                
               lstLogToUpdate.add(objNewLog); 
            }
            
            
        }
        if(!lstEmailsToSend.isEmpty()){
            Messaging.sendEmail(lstEmailsToSend);
        }
        if(!lstLinksToCreate.isEmpty()){
            insert lstLinksToCreate;
        }
        if(!lstLogToUpdate.isEmpty()){
            bByPassTrigger = true;
			update lstLogToUpdate;            
        }
        if(!lstLog.isEmpty()){
            insert lstLog;
        }
        
    }
    
    public static void generateLog(List<Document_Generation_Log__c> lstRecords){
        List<Log_Records__c> lstLog = new List<Log_Records__c>();
        for(Document_Generation_Log__c objLog: lstRecords){
            Log_Records__c objLogRecord = new Log_Records__c();
           	objLogRecord.Type__c = 'Initiation';
            objLogRecord.Document_Generation_Log__c = objLog.Id;
            lstLog.add(objLogRecord);
            //objLog.Complete_Log__c = 'Document Generated by '+UserInfo.getName()+' at '+System.now();
        }
        if(!lstLog.isEmpty()){
            insert lstLog;
        }
    }
    
    

}