force-app/main/default/objects/Data_Mapping__c/Data_Mapping__c.object-meta.xml
<CustomObject>
    <label>Data Mapping</label>
    <nameField>
        <displayFormat>DMR #{0}</displayFormat>
        <label>Data Mapping Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Mapping</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Mapping__c/fields/Document_Template__c.field-meta.xml
<CustomField>
    <fullName>Document_Template__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Document Template</label>
    <referenceTo>Document_Template__c</referenceTo>
    <relationshipLabel>Data Mapping</relationshipLabel>
    <relationshipName>Data_Mapping</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Data_Mapping__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Data_Mapping__c/fields/Salesforce_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Field_API_Name__c</fullName>
    <label>Salesforce Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Mapping__c/fields/Template_Field__c.field-meta.xml
<CustomField>
    <fullName>Template_Field__c</fullName>
    <label>Template Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Template__c/Document_Template__c.object-meta.xml
<CustomObject>
    <description>This object will store the templates to be used to generate documents.</description>
    <label>Document Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Template__c/fields/Template_Type__c.field-meta.xml
<CustomField>
    <fullName>Template_Type__c</fullName>
    <description>This field will store the type of file used as template</description>
    <label>Template Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DocumentViewer.cls
public class DocumentViewer {
    
    @AuraEnabled
    public static Map<String, Object> getTemplates(Map<String, Object> mapInputParams){
        String sRecordId = (String)mapInputParams.get('recordId');
        Map<String, Object> mapOutputVar = new Map<String, Object>();
        mapOutputVar.put('isSuccess', true);
        try{
            if(sRecordId != NULL){
                List<Object> lstFields = new List<Object>(); 
                String sObjName = Id.valueOf(sRecordId).getSObjectType().getDescribe().getName();
                List<Document_Template__c> lstTemplates = [Select Id,Document_Title__c from Document_Template__c Where Template_Type__c =: sObjName];
                if(!lstTemplates.isEmpty()){
                    for(Document_Template__c objTemp : lstTemplates){
                        dropDownOptions ddOptions = new dropDownOptions();
                        ddOptions.label = objTemp.Document_Title__c;
                        ddOptions.value = objTemp.Id;
                        lstFields.add(JSON.serialize(ddOptions));
                    }
                    if(!lstFields.isEmpty()){
                        mapOutputVar.put('dropDownOptions', lstFields);
                    }
                }
            }
        } catch(Exception ex){
            mapOutputVar.put('isSuccess', false);
            mapOutputVar.put('errorMsg', ex.getMessage());
        }
        return mapOutputVar;
    }
    
    public static void getTemplateDetails(Map<String, Object> mapInputParams){
        String sTemplateId= (String)mapInputParams.get('TemplateId');
        String sRecordId = (String)mapInputParams.get('recordId');
        Map<String, String> mapFieldValue = new Map<String, String>();
        
        if(sTemplateId != NULL){
            List<Data_Mapping__c> lstMapping = [SELECT Id, Document_Template__c, Template_Field__c, Salesforce_Field_API_Name__c from Data_Mapping__c 
                                                Where isActive__c = true AND Document_Template__c =: sTemplateId];
            if(!lstMapping.isEmpty()){
                Set<String> setFields = new Set<String>();
                for(Data_Mapping__c objMap : lstMapping){
                    setFields.add(objMap.Salesforce_Field_API_Name__c);
                } 
                if(!setFields.isEmpty() && sRecordId != NULL && sRecordId != ''){
                    String sObjName = Id.valueOf(sRecordId).getSObjectType().getDescribe().getName();
                    String sQuery = 'Select Id,'+String.join(new List<String>(setFields),', ')+' FROM '+sObjName+' Where Id=\''+sRecordId+'\'';
                    sObject objData = Database.query(sQuery)[0];
                    system.debug('Data : '+objData);
                    Map<String, String> mapAPIValue = new Map<String, String>();
                    for(String sField :setFields){
                       mapAPIValue.put(sField, (String)objData.get(sField));
                    }
                    for(Data_Mapping__c objMap : lstMapping){
                    	 mapFieldValue.put(objMap.Template_Field__c, mapAPIValue.get(objMap.Salesforce_Field_API_Name__c));
                	}
                    
                }
                
            }
            
        }
        
    }
    
    public class dropDownOptions{
    	public string label;
    	public string value;
	}
    public class instanceJSON{
    	public string format;
    	public formFieldValue[] formFieldValues;
	}
    public class formFieldValue{
        public string v;
        public string stype;
        public string sname;
        public string value;
    }
}